/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebaimagenes;

import java.awt.*;
import java.io.File;
import java.io.IOException;
import javax.imageio.*;

/**
 *
 * @author eduwo
 */
public class LaminaConImagen extends javax.swing.JPanel {

    private Image imagen;

  

    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        File miImagen = new File("src/tipos.pn");
        
        try {
            imagen = ImageIO.read(miImagen);
            
        } catch (IOException ex) {
            
            System.out.println("Error en la lectura de la imagen.");
            System.out.println(ex.getMessage());      
        }
        g.drawImage(imagen, 5, 5, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
